import Navbar from '@/components/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SideMenu from '@/components/SideMenu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" data-theme="night">
			<body className={inter.className}>
				{/* <Navbar /> */}
				<div className="flex  ">
					<SideMenu />
					<div className="w-full">{children}</div>
				</div>
			</body>
		</html>
	);
}
